### ISSUE TITLE
"ok":true often missing from responses

### ISSUE THREAD

**Issue by rooklift** [eu90h/stockfighter-racket#2]
"ok" : true should usually be present in the JSON for any valid request. (Also for websocket messages, which I haven't looked at.)

It is currently missing from responses to order placement, from the status, and from the orderbook.

[Edit: I think I posted this to the wrong repository, it should have been a mockfighter issue. But since you're the maintainer for both, I'll just leave this here.]

**Comment by eu90h** [comment]
Really sorry about that one, silly mistake. Fixed, thanks.
